# Generated by Django 4.1 on 2022-10-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
