# Generated by Django 4.2 on 2023-04-27 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_user_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="file",),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("imagen", models.FileField(upload_to="")),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
                    ),
                ),
            ],
        ),
    ]
