# Generated by Django 4.2 on 2023-05-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_image_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('participantes', models.IntegerField(verbose_name='Participantes')),
                ('objetivo', models.CharField(max_length=500, verbose_name='Objetivo')),
                ('descripcion', models.CharField(max_length=2000, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoria'),
        ),
    ]
