# Generated by Django 4.2 on 2023-05-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_actividad_categoria_delete_image_delete_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="mainapp.categoria",
            ),
        ),
    ]
