# Generated by Django 4.2 on 2023-05-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_actividad_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="mainapp.categoria",
            ),
        ),
    ]
